// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: reasons/reasons.proto

package reasons

import (
	_ "github.com/nexuer/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reason int32

const (
	Reason_INTERNAL_SERVER_ERROR Reason = 0
	Reason_NOT_FOUND             Reason = 1
	Reason_BAD_REQUEST           Reason = 2
	Reason_UNAUTHORIZED          Reason = 3
	Reason_FORBIDDEN             Reason = 4
	Reason_CONFLICT              Reason = 5
	Reason_TOO_MANY_REQUESTS     Reason = 6
	Reason_CLIENT_CLOSED         Reason = 7
	Reason_SERVICE_UNAVAILABLE   Reason = 8
	Reason_GATEWAY_TIMEOUT       Reason = 9
	Reason_REQUEST_TOO_LARGE     Reason = 10
	Reason_CODEC                 Reason = 11
	Reason_NOT_ACCEPTABLE        Reason = 12
)

// Enum value maps for Reason.
var (
	Reason_name = map[int32]string{
		0:  "INTERNAL_SERVER_ERROR",
		1:  "NOT_FOUND",
		2:  "BAD_REQUEST",
		3:  "UNAUTHORIZED",
		4:  "FORBIDDEN",
		5:  "CONFLICT",
		6:  "TOO_MANY_REQUESTS",
		7:  "CLIENT_CLOSED",
		8:  "SERVICE_UNAVAILABLE",
		9:  "GATEWAY_TIMEOUT",
		10: "REQUEST_TOO_LARGE",
		11: "CODEC",
		12: "NOT_ACCEPTABLE",
	}
	Reason_value = map[string]int32{
		"INTERNAL_SERVER_ERROR": 0,
		"NOT_FOUND":             1,
		"BAD_REQUEST":           2,
		"UNAUTHORIZED":          3,
		"FORBIDDEN":             4,
		"CONFLICT":              5,
		"TOO_MANY_REQUESTS":     6,
		"CLIENT_CLOSED":         7,
		"SERVICE_UNAVAILABLE":   8,
		"GATEWAY_TIMEOUT":       9,
		"REQUEST_TOO_LARGE":     10,
		"CODEC":                 11,
		"NOT_ACCEPTABLE":        12,
	}
)

func (x Reason) Enum() *Reason {
	p := new(Reason)
	*p = x
	return p
}

func (x Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_reasons_reasons_proto_enumTypes[0].Descriptor()
}

func (Reason) Type() protoreflect.EnumType {
	return &file_reasons_reasons_proto_enumTypes[0]
}

func (x Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reason.Descriptor instead.
func (Reason) EnumDescriptor() ([]byte, []int) {
	return file_reasons_reasons_proto_rawDescGZIP(), []int{0}
}

var File_reasons_reasons_proto protoreflect.FileDescriptor

const file_reasons_reasons_proto_rawDesc = "" +
	"\n" +
	"\x15reasons/reasons.proto\x12\areasons\x1a\ferrors.proto*\xce\x02\n" +
	"\x06Reason\x12\x19\n" +
	"\x15INTERNAL_SERVER_ERROR\x10\x00\x12\x13\n" +
	"\tNOT_FOUND\x10\x01\x1a\x04\xa8E\x94\x03\x12\x15\n" +
	"\vBAD_REQUEST\x10\x02\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fUNAUTHORIZED\x10\x03\x1a\x04\xa8E\x91\x03\x12\x13\n" +
	"\tFORBIDDEN\x10\x04\x1a\x04\xa8E\x93\x03\x12\x12\n" +
	"\bCONFLICT\x10\x05\x1a\x04\xa8E\x99\x03\x12\x1b\n" +
	"\x11TOO_MANY_REQUESTS\x10\x06\x1a\x04\xa8E\xad\x03\x12\x17\n" +
	"\rCLIENT_CLOSED\x10\a\x1a\x04\xa8E\xf3\x03\x12\x1d\n" +
	"\x13SERVICE_UNAVAILABLE\x10\b\x1a\x04\xa8E\xf7\x03\x12\x19\n" +
	"\x0fGATEWAY_TIMEOUT\x10\t\x1a\x04\xa8E\xf8\x03\x12\x1b\n" +
	"\x11REQUEST_TOO_LARGE\x10\n" +
	"\x1a\x04\xa8E\x9d\x03\x12\x0f\n" +
	"\x05CODEC\x10\v\x1a\x04\xa8E\x90\x03\x12\x18\n" +
	"\x0eNOT_ACCEPTABLE\x10\f\x1a\x04\xa8E\x96\x03\x1a\x04\xa0E\xf4\x03BN\n" +
	" com.github.nexuer.errors.reasonsP\x01Z(github.com/nexuer/errors/reasons;reasonsb\x06proto3"

var (
	file_reasons_reasons_proto_rawDescOnce sync.Once
	file_reasons_reasons_proto_rawDescData []byte
)

func file_reasons_reasons_proto_rawDescGZIP() []byte {
	file_reasons_reasons_proto_rawDescOnce.Do(func() {
		file_reasons_reasons_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reasons_reasons_proto_rawDesc), len(file_reasons_reasons_proto_rawDesc)))
	})
	return file_reasons_reasons_proto_rawDescData
}

var file_reasons_reasons_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_reasons_reasons_proto_goTypes = []any{
	(Reason)(0), // 0: reasons.Reason
}
var file_reasons_reasons_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reasons_reasons_proto_init() }
func file_reasons_reasons_proto_init() {
	if File_reasons_reasons_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reasons_reasons_proto_rawDesc), len(file_reasons_reasons_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reasons_reasons_proto_goTypes,
		DependencyIndexes: file_reasons_reasons_proto_depIdxs,
		EnumInfos:         file_reasons_reasons_proto_enumTypes,
	}.Build()
	File_reasons_reasons_proto = out.File
	file_reasons_reasons_proto_goTypes = nil
	file_reasons_reasons_proto_depIdxs = nil
}
