// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package reasons

import (
	errors "github.com/nexuer/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the errors package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsInternalServerError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_INTERNAL_SERVER_ERROR.String() && e.Code == 500
}

func ErrorInternalServerError(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(500, Reason_INTERNAL_SERVER_ERROR.String(), format, args...)
	}
	return errors.New(500, Reason_INTERNAL_SERVER_ERROR.String(), format)
}

func IsNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_NOT_FOUND.String() && e.Code == 404
}

func ErrorNotFound(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(404, Reason_NOT_FOUND.String(), format, args...)
	}
	return errors.New(404, Reason_NOT_FOUND.String(), format)
}

func IsBadRequest(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_BAD_REQUEST.String() && e.Code == 400
}

func ErrorBadRequest(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(400, Reason_BAD_REQUEST.String(), format, args...)
	}
	return errors.New(400, Reason_BAD_REQUEST.String(), format)
}

func IsUnauthorized(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_UNAUTHORIZED.String() && e.Code == 401
}

func ErrorUnauthorized(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(401, Reason_UNAUTHORIZED.String(), format, args...)
	}
	return errors.New(401, Reason_UNAUTHORIZED.String(), format)
}

func IsForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_FORBIDDEN.String() && e.Code == 403
}

func ErrorForbidden(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(403, Reason_FORBIDDEN.String(), format, args...)
	}
	return errors.New(403, Reason_FORBIDDEN.String(), format)
}

func IsConflict(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_CONFLICT.String() && e.Code == 409
}

func ErrorConflict(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(409, Reason_CONFLICT.String(), format, args...)
	}
	return errors.New(409, Reason_CONFLICT.String(), format)
}

func IsTooManyRequests(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_TOO_MANY_REQUESTS.String() && e.Code == 429
}

func ErrorTooManyRequests(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(429, Reason_TOO_MANY_REQUESTS.String(), format, args...)
	}
	return errors.New(429, Reason_TOO_MANY_REQUESTS.String(), format)
}

func IsClientClosed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_CLIENT_CLOSED.String() && e.Code == 499
}

func ErrorClientClosed(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(499, Reason_CLIENT_CLOSED.String(), format, args...)
	}
	return errors.New(499, Reason_CLIENT_CLOSED.String(), format)
}

func IsServiceUnavailable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_SERVICE_UNAVAILABLE.String() && e.Code == 503
}

func ErrorServiceUnavailable(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(503, Reason_SERVICE_UNAVAILABLE.String(), format, args...)
	}
	return errors.New(503, Reason_SERVICE_UNAVAILABLE.String(), format)
}

func IsGatewayTimeout(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_GATEWAY_TIMEOUT.String() && e.Code == 504
}

func ErrorGatewayTimeout(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(504, Reason_GATEWAY_TIMEOUT.String(), format, args...)
	}
	return errors.New(504, Reason_GATEWAY_TIMEOUT.String(), format)
}

func IsRequestEntityTooLarge(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_REQUEST_ENTITY_TOO_LARGE.String() && e.Code == 413
}

func ErrorRequestEntityTooLarge(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(413, Reason_REQUEST_ENTITY_TOO_LARGE.String(), format, args...)
	}
	return errors.New(413, Reason_REQUEST_ENTITY_TOO_LARGE.String(), format)
}

func IsCodec(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_CODEC.String() && e.Code == 400
}

func ErrorCodec(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(400, Reason_CODEC.String(), format, args...)
	}
	return errors.New(400, Reason_CODEC.String(), format)
}

func IsNotAcceptable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_NOT_ACCEPTABLE.String() && e.Code == 406
}

func ErrorNotAcceptable(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(406, Reason_NOT_ACCEPTABLE.String(), format, args...)
	}
	return errors.New(406, Reason_NOT_ACCEPTABLE.String(), format)
}

func IsMethodNotAllowed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_METHOD_NOT_ALLOWED.String() && e.Code == 405
}

func ErrorMethodNotAllowed(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(405, Reason_METHOD_NOT_ALLOWED.String(), format, args...)
	}
	return errors.New(405, Reason_METHOD_NOT_ALLOWED.String(), format)
}

func IsUnsupportedMediaType(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_UNSUPPORTED_MEDIA_TYPE.String() && e.Code == 415
}

func ErrorUnsupportedMediaType(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(415, Reason_UNSUPPORTED_MEDIA_TYPE.String(), format, args...)
	}
	return errors.New(415, Reason_UNSUPPORTED_MEDIA_TYPE.String(), format)
}

func IsBadGateway(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Reason_BAD_GATEWAY.String() && e.Code == 502
}

func ErrorBadGateway(format string, args ...any) *errors.Error {
	if len(args) > 0 {
		return errors.Newf(502, Reason_BAD_GATEWAY.String(), format, args...)
	}
	return errors.New(502, Reason_BAD_GATEWAY.String(), format)
}
